### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
## 1 DIMENSIONAL ARRAY
# to secify the type we want it to store as: dtype='int32'
# the bigger the number the larger the bytes that are used to store the data
a = np.array([1,2,3], dtype='int16') 
print(a)

[1 2 3]


In [3]:
## 2 DIMENSIONAL ARRAY 
## A LIST WITHIN A LIST
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim
b.ndim

2

In [5]:
# Get Shape
b.shape ## the rows and columns 

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int16')

In [7]:
# Get Size
a.itemsize

2

In [8]:
# Get total size
a.nbytes ##(a.size*a.itemsize)

6

In [9]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a.shape ## 2 rows, 7 columns

(2, 7)

In [12]:
# Get a specific element [real index, columnindex]
a[1, 5] #python starts with 0, so row 0 = first, row 1= 2nd

13

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column, all rows, but column 3
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
#a[0] #row 1
#a[0,1] #column 2
#a[0,1:6] #column 2 to column 6
a[0,1:6:2]  # step  by 2 elements, so 2,4,6

array([2, 4, 6])

In [17]:
a[1,5] = 20 # row 2 column 5 now is 20

a[:,2] =5 ## all column 3 will be 5s


## add diff numbers 

a[:,2] = [1,2]


print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [18]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Get specific element (work outside in)
b[0,1,1] ## first set, second row, first (second) element

4

In [20]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [22]:
# All 0s matrix
#np.zeros((3))   ## an array with 3 0s

#np.zeros((2,3))  ## 2 lists with each 3 0s
# array([[0., 0., 0.],
#        [0., 0., 0.]])


#np.zeros((2,3,3))  ## 2 lists with 3 lists inside where each  has 3 0s

# array([[[0., 0., 0.],
#         [0., 0., 0.],
#         [0., 0., 0.]],

#        [[0., 0., 0.],
#         [0., 0., 0.],
#         [0., 0., 0.]]])


np.zeros((2,3,3,2))  # 
# array([[[[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]]],


#        [[[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]],

#         [[0., 0.],
#          [0., 0.],
#          [0., 0.]]]])

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [25]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.35318983, 0.05110996],
       [0.81153172, 0.92975548],
       [0.9890495 , 0.69498929],
       [0.47108953, 0.4931587 ]])

In [27]:
# Random Integer values
np.random.randint(-10,20, size=(3,3))

array([[-2,  1, 18],
       [19, 15, -7],
       [18, 14,  9]])

In [28]:
np.random.random_sample(a.shape)

array([[0.83611002, 0.40580073, 0.13037472, 0.54134884, 0.57134543,
        0.66907887, 0.36439711],
       [0.86022745, 0.33966294, 0.6975182 , 0.00310484, 0.25888522,
        0.87922266, 0.85882816]])

In [29]:
# The identity matrix (matrices with 1s and 0s) always gonna be a square
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array
arr = np.array([[1,2,3]]) ## the double [] means that the numbers in the inner [ will be repeated]
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [32]:

## we have to tell numpy that we want to create a copy of the variable, 
## it shouldn't connect a and b togetehr or else the a content will be lsot too

a = np.array([1,2,3])
b = a

b[0] = 100

print(a) ## the first digit 1 gets lost so:

a= np.array([1,2,3])
b=a.copy()

b[0]=100
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [40]:
a+=2
print(a)

[5 6 7 8]


In [36]:
a-2

array([-1,  0,  1,  2])

In [37]:
a*2

array([2, 4, 6, 8])

In [38]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [43]:
b= np.array([1,0,1,0])

a+b

array([2, 2, 4, 4])

In [49]:
## powers

a**2

array([ 1,  4,  9, 16], dtype=int32)

In [53]:
## take the sin of values


np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [61]:
a= np.ones((2,3))  ## two rows, three columns of 1s

print(a)


## linear algebra  = the columns of first matrix has to be equal
# to the rows of the second matirx


b = np.full((3,2),2)  ## three rows, 2 columns of 2s 
print(b) 


## multiplying both matrices
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [62]:
# to find the determinate of the matrix

c= np.identity(3)

np.linalg.det(c)



1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [63]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.min(stats,axis=1) ## axis= row bases

array([1, 4])

In [67]:
np.max(stats, axis= 1) ## max in both rows

array([3, 6])

In [69]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [72]:
## chnaging the shape of the matrix

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [80]:
## Vertically stacking vectors
## the sizes of both stacks have to be the same


v1= np.array([1,2,3,4])
print(v1)
v2= np.array([5,6,7,8])
print(v2)          


np.vstack([v1,v2])

[1 2 3 4]
[5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
## Horizontal stack

h1= np.ones((2,4))

h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [91]:
filedata=np.genfromtxt("data.txt", delimiter=",")  ## naturally it would be a float

## change it into an integer

filedata=filedata.astype("int32")

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [93]:
filedata >=50 ## get position of where there is true or false

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [95]:
filedata[filedata > 50] ## only grabs values that are greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [98]:
## index with a list in numpy
aa=np.array([1,2,3,4,5,6,7,8,9])

aa[[1,2,8]]

array([2, 3, 9])

In [99]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [101]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [103]:
((filedata > 50 ) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [104]:
## the reverse

(~((filedata > 50 ) & (filedata <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [116]:
qs= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
             21,22,23,24,25,26,27,28,29,30])


qs=qs.reshape((6,5))

#print(qs)

first=qs[2:4,0:2]
print(first)


[[11 12]
 [16 17]]


In [123]:
# Getting a little more fancy [startindex:endindex:stepsize]
second=qs[[0,1,2,3],[1,2,3,4]]

print(second)

[ 2  8 14 20]


In [127]:
third= qs[[0,4,5],3:]
print(third)

[[ 4  5]
 [24 25]
 [29 30]]
